/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad1bingo;

import javax.swing.JOptionPane;

/**
 *
 * @author Tarde
 */
public class Bingo extends javax.swing.JFrame {

    static int carton[][] = new int[5][5];
    private boolean ganar=false;
    /**
     * Creates new form Bingo
     */
    public Bingo() {
        Actividad1_Bingo a = new Actividad1_Bingo();
        initComponents();
        carton = (int[][]) a.mostrarCarton();
        jTextArea.setText(verCarton());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonGenerarNumero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea.setRows(5);
        jPanel1.add(jTextArea);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 404, 156));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 53, 30));

        jButtonGenerarNumero.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonGenerarNumero.setText("Generar número");
        jButtonGenerarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGenerarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/barajar.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 190, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNumeroActionPerformed
        int n = 0;
        n = (int) (Math.random() * 75) + 1;
   
            jLabel1.setText(n + "");
            if (buscaNum(n)) {
                //Cambiamos el numero encontrado por un "0"
                cambiarNum(n);
                //Ver el carton en su nuevo estado 
                jTextArea.setText(verCarton());
               
                //Comprobamos si el jugador gano o  no
                //Se gana si se completa una fila entera, una columna o una diagonal   
                ganar = comprobarEstado();
                if(ganar){
                   jButtonGenerarNumero.setEnabled(false); 
                }
            }        
    }//GEN-LAST:event_jButtonGenerarNumeroActionPerformed

    private boolean comprobarEstado() {

        //Comprobar si alguna fila esta completa
        int f = 0;
         ganar = false;
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (carton[fila][col] == 0) {
                    f++;
                }
            }
            if (f == 5) {
                ganar = true;
                JOptionPane.showMessageDialog(this, "Completaste una fila", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);
                return ganar;
            } else {
                f = 0;
            }
        }
        //Comprobar si alguna columna esta completa
        f = 0;
        for (int col = 0; col < 5; col++) {
            for (int fila = 0; fila < 5; fila++) {
                if (carton[fila][col] == 0) {
                    f++;
                }
            }
            if (f == 5) {
                ganar = true;
                JOptionPane.showMessageDialog(this, "Completaste una columna", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

                return ganar;
            } else {
                f = 0;
            }
        }

        //Comprobar la diagonal que empieza en 00 
        f = 0;
        for (int i = 0; i < 5; i++) {
            
                    if (carton[i][i] == 0) {
                        f++;
            }
        }
        if (f == 5) {
            ganar = true;
            JOptionPane.showMessageDialog(this, "Completaste una diagonal", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

            return ganar;
        } 

        //Comprobar la segunda diagonal
        f = 0;
        ganar = false;
        int col = 4;
        for (int fila = 0; fila < 5; fila++) {

            if (carton[fila][col] == 0) {
                f++;

            }
            col--;
        }
        if (f == 5) {
            ganar = true;
            JOptionPane.showMessageDialog(this, "Completaste una diagonal", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

            return ganar;
        } 

        return ganar;

    }

    private void cambiarNum(int valor) {
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (valor == carton[fila][col]) {
                    carton[fila][col] = 0;
                }
            }
        }
    }

    public static boolean buscaNum(int valor) {
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (valor == carton[fila][col]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static String verCarton() {
        String mensaje = "";
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                mensaje = mensaje + carton[fila][col] + "\t";
            }
            mensaje = mensaje + "\n";
        }
        return mensaje;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

}
