/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class Editar extends JDialog {

    /**
     * Creates new form Editar
     */
    public Editar(JFrame padre, String contenido) {
        super(padre, true);
        initComponents();
        //Hace que en el textArea se muestre lo que el usuario metio anteriormente 
        //en la tarea.
        this.jTextArea.setText(contenido);

    }

    public JTextArea getjTextArea2() {
        return jTextArea;
    }

    public void setjTextArea2(JTextArea jTextArea2) {
        this.jTextArea = jTextArea2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jPanelBoton = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 200));
        setResizable(false);

        jPanelGeneral.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelGeneral.setLayout(new java.awt.BorderLayout());

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea);

        jPanelGeneral.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBoton.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanelBoton.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCerrar.setBackground(new java.awt.Color(0, 102, 204));
        jButtonCerrar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(0, 0, 102));
        jButtonCerrar.setText("Guardar cambios");
        jButtonCerrar.setBorderPainted(false);
        jButtonCerrar.setFocusPainted(false);
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanelBoton.add(jButtonCerrar);

        jPanelGeneral.add(jPanelBoton, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        //Cierra el jDialog 
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    public String textomod() {
        //recoge lo que el usuario introdujo en el jTextArea
        return this.jTextArea.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
