/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class GestorTareas extends javax.swing.JDialog {

    int contadorT = 0;

    public int getContadorT() {
        return contadorT;
    }

    public void setContadorT(int contadorT) {
        this.contadorT = contadorT;
    }

    /**
     * Creates new form GestorTareas
     */
    public GestorTareas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public GestorTareas() {
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnañadir = new javax.swing.JButton();
        jPanelañadirT = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(255, 255, 255)));
        jPanel1.setToolTipText("");

        jPanel3.setLayout(new java.awt.BorderLayout());

        btnañadir.setBackground(new java.awt.Color(0, 0, 102));
        btnañadir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnañadir.setForeground(new java.awt.Color(255, 255, 255));
        btnañadir.setText("Añadir tarea");
        btnañadir.setBorderPainted(false);
        btnañadir.setFocusPainted(false);
        btnañadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnañadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnañadirMouseExited(evt);
            }
        });
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });
        jPanel3.add(btnañadir, java.awt.BorderLayout.CENTER);

        jPanelañadirT.setPreferredSize(new java.awt.Dimension(379, 250));
        jPanel3.add(jPanelañadirT, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tareas pendientes", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tareas completadas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnañadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnañadirMouseEntered
        btnañadir.setBackground(Color.darkGray);
    }//GEN-LAST:event_btnañadirMouseEntered

    private void btnañadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnañadirMouseExited
        btnañadir.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_btnañadirMouseExited

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
        String tarea = JOptionPane.showInputDialog(this, "¿Sobre que será la tarea a añadir?: ", "Añadir tarea", JOptionPane.PLAIN_MESSAGE);
        paneltarea(tarea);
        this.setContadorT(contadorT + 1);
    }//GEN-LAST:event_btnañadirActionPerformed

    private void paneltarea(String mensaje) {
        Tarea t = new Tarea();
        if (this.getContadorT() < 9) {
            if (mensaje != null && !mensaje.isEmpty() && !mensaje.trim().equals("")) {
                t.nuevoMensaje(mensaje);
                jPanelañadirT.add(t);
                jPanelañadirT.revalidate();
                jPanelañadirT.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "Estás intentando introducir una tarea vacía.", "Tarea vacía", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "No se pueden añadir más de 9 tareas.\n Elimina o completa alguna tarea para añadir una nueva", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }
    
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestorTareas dialog = new GestorTareas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelañadirT;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
