/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.oculto.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/icon.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        oculto = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/seguridad-del-usuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cerrar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 70));

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, 40));

        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iniciar-sesion.png"))); // NOI18N
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 236, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/letra-x.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setText("Bienvenid@!");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 16, 207, 50));
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 176, 211, 44));

        oculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/oculto.png"))); // NOI18N
        oculto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultoMouseClicked(evt);
            }
        });
        jPanel1.add(oculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 50, 50));

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ojo.png"))); // NOI18N
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel1.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        String usuario, contraseña;
        usuario = txt_user.getText();
        contraseña = String.valueOf(txt_pass.getPassword());
        if (usuario.equals("admin") && contraseña.equals("admin")) {
            JOptionPane.showMessageDialog(this, "Accediste con exito", "Login correcto", WIDTH);
            AudioClip Sound;
            Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audios/Login.wav"));
            Sound.play();
            this.dispose();
            GestorTareasF tareas = new GestorTareasF();
            // Hacemos visible la ventana
            tareas.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Error.Revisa login o contraseña", "Login incorrecto", JOptionPane.ERROR_MESSAGE);
            txt_user.setText("");
            txt_pass.setText("");

        }
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿Esta usted seguro de salir?", "SALIR", a);

        if (resultado == 0) {
            this.dispose();

        }
    }//GEN-LAST:event_salirMouseClicked

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        ver.setVisible(false);
        oculto.setVisible(true);
        txt_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_verMouseClicked

    private void ocultoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultoMouseClicked
        ver.setVisible(true);
        oculto.setVisible(false);
        txt_pass.setEchoChar('*');
    }//GEN-LAST:event_ocultoMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oculto;
    private javax.swing.JLabel salir;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
