/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import javax.swing.JLabel;

/**
 *
 * @author fatmo
 */
public class Tarea extends javax.swing.JPanel {

    /**
     * Creates new form tarea
     */
    public Tarea() {
        initComponents();
    } 

    public JLabel getjLabelMensaje() {
        return jLabelMensaje;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        setPreferredSize(new java.awt.Dimension(240, 80));
        setLayout(new java.awt.BorderLayout());

        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText("Tarea");
        jLabelMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMensajeMouseClicked(evt);
            }
        });
        add(jLabelMensaje, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Completada");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       java.awt.Container padre=this.getParent();
       
       padre.remove(this);
       padre.revalidate();
       padre.repaint();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jLabelMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMensajeMouseClicked
        GestorTareas p=new GestorTareas(); 
        Editar ed=new Editar(p, jLabelMensaje.getText());
        ed.setVisible(true);
        
        String textmod=ed.textomod();
        if(textmod!=null && !textmod.trim().isEmpty()){
            jLabelMensaje.setText(textmod); 
        }
       
        
        java.awt.Container padre=this.getParent();
        padre.revalidate();
       padre.repaint();
            
        
        
    }//GEN-LAST:event_jLabelMensajeMouseClicked

   
    public void nuevoMensaje(String m){
        jLabelMensaje.setText(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
