/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class GestorTareasF extends javax.swing.JFrame {

    //Modelo de tabla para almacenar las tareas completadas 
    private DefaultTableModel modeloTabla;
    //Contador para establecer y controlar las tareas en el panel principal. 
    int contadorT = 0;

    /**
     * Creates new form GestorTareasF
     */
    public GestorTareasF() {

        initComponents();

        modeloTabla = new DefaultTableModel() { //Define el modelo de la tabla 
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //Evita que las celdas de la tabla sean editables. 
            }
        };
        modeloTabla.addColumn("Tarea completada"); //Añade columna para la tarea 
        modeloTabla.addColumn("Fecha finalización"); //Añade columna para la fecha
        jTabla.setModel(modeloTabla); //Asigna el modelo de la tabla a jTable
        //Poner el icono a la ventana 
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/icon.png")).getImage());
        //cambia el fondo al boton aunque al usar laf no se aplicaria. 
        btnañadir.setBackground(new Color(0, 0, 102));
    }

    public int getContadorT() {
        return contadorT;
    }

    public void setContadorT(int contadorT) {
        this.contadorT = contadorT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnañadir = new javax.swing.JButton();
        jPanelañadirT = new javax.swing.JPanel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jPanelEleccion = new javax.swing.JPanel();
        jPanelImgs = new javax.swing.JPanel();
        jLabelCompra = new javax.swing.JLabel();
        jLabelCuidarAnimales = new javax.swing.JLabel();
        jLabelCuidarPlantas = new javax.swing.JLabel();
        jLabelCorrer = new javax.swing.JLabel();
        jLabelPeluqueria = new javax.swing.JLabel();
        jLabelLeer = new javax.swing.JLabel();
        jpanelTitulo1 = new jpanelPersonalizado.JpanelTitulo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFocusable(false);
        jTabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnañadir.setBackground(new java.awt.Color(0, 0, 102));
        btnañadir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnañadir.setForeground(new java.awt.Color(0, 0, 102));
        btnañadir.setText("Añadir tarea");
        btnañadir.setBorderPainted(false);
        btnañadir.setFocusPainted(false);
        btnañadir.setMaximumSize(new java.awt.Dimension(110, 5));
        btnañadir.setMinimumSize(new java.awt.Dimension(110, 15));
        btnañadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnañadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnañadirMouseExited(evt);
            }
        });
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });
        jPanel3.add(btnañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 660, 30));

        jPanelañadirT.setBackground(new java.awt.Color(255, 255, 255));
        jPanelañadirT.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanelañadirT.setPreferredSize(new java.awt.Dimension(740, 260));
        jPanelañadirT.setRequestFocusEnabled(false);
        jPanel3.add(jPanelañadirT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 660, 320));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Tareas pendientes", jPanel1);

        jPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTabla.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTabla.setForeground(new java.awt.Color(0, 0, 102));
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jPanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab("Tareas completadas", jPanelTabla);

        jPanelEleccion.setBackground(new java.awt.Color(255, 255, 255));

        jPanelImgs.setLayout(new java.awt.GridLayout(2, 3));

        jLabelCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/compras.png"))); // NOI18N
        jLabelCompra.setToolTipText("Hacer la compra");
        jLabelCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCompraMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelCompra);

        jLabelCuidarAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cuidarMascota.png"))); // NOI18N
        jLabelCuidarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCuidarAnimalesMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelCuidarAnimales);

        jLabelCuidarPlantas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cuidarPlanta.png"))); // NOI18N
        jLabelCuidarPlantas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCuidarPlantasMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelCuidarPlantas);

        jLabelCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deporte.png"))); // NOI18N
        jLabelCorrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorrerMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelCorrer);

        jLabelPeluqueria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/peluqueria.png"))); // NOI18N
        jLabelPeluqueria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeluqueriaMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelPeluqueria);

        jLabelLeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/leer.png"))); // NOI18N
        jLabelLeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLeerMouseClicked(evt);
            }
        });
        jPanelImgs.add(jLabelLeer);

        javax.swing.GroupLayout jPanelEleccionLayout = new javax.swing.GroupLayout(jPanelEleccion);
        jPanelEleccion.setLayout(jPanelEleccionLayout);
        jPanelEleccionLayout.setHorizontalGroup(
            jPanelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEleccionLayout.createSequentialGroup()
                .addGroup(jPanelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEleccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpanelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEleccionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanelImgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelEleccionLayout.setVerticalGroup(
            jPanelEleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEleccionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jpanelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanelImgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Tareas recomendadas", jPanelEleccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnañadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnañadirMouseEntered
        btnañadir.setBackground(Color.darkGray); //cambiaria el color al pasar el raton por encima del boton de añadir. 
    }//GEN-LAST:event_btnañadirMouseEntered

    private void btnañadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnañadirMouseExited
        btnañadir.setBackground(new Color(0, 0, 102));  //restablece el color al sacar el raton del boton 
    }//GEN-LAST:event_btnañadirMouseExited


    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
        //Nos pregunta sobre el asunto de nuestra tarea y llama al método que añadira la tarea. 
        String tarea = JOptionPane.showInputDialog(this, "¿Sobre que será la tarea a añadir?: ", "Añadir tarea", JOptionPane.PLAIN_MESSAGE);
        paneltarea(tarea);

    }//GEN-LAST:event_btnañadirActionPerformed

    //Añade una nueva tarea al panel y aumenta el contador si la tarea es valida. 
    private void paneltarea(String mensaje) {
        Tarea t = new Tarea(this); //Creamos una instancia de la clase tarea 
        if (this.getContadorT() < 6) { //Verificamos si el limite de tareas no se ha alcanzado 

            if (mensaje != null && !mensaje.isEmpty() && !mensaje.trim().equals("")) {
                t.nuevoMensaje(mensaje); //le metemos el mensaje de la tarea 
                jPanelañadirT.add(t); //añadimos la tarea al panel 
                jPanelañadirT.revalidate(); //refrescamos el panel 
                jPanelañadirT.repaint(); //lo volvemos a dibujar el panel 
                this.setContadorT(contadorT + 1); //incrementamos el contador de tareas 
            } else {
                //Mensaje de advertencia si el usuario intenta añadir una tarea vacia
                JOptionPane.showMessageDialog(this, "Estás intentando introducir una tarea vacía.", "Tarea vacía", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            //Mensaje de error si el usuario excede el limite de tareas establecido 
            JOptionPane.showMessageDialog(this, "No se pueden añadir más de 6 tareas.\n Elimina o completa alguna tarea para añadir una nueva", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }

    //Agregamos una tarea completada a la tabla tareas completadas con la fecha actual 
    public void agregarTareaC(String tarea, String fecha) {
        modeloTabla.addRow(new Object[]{tarea, fecha});
    }

    //Pregunta al usuario si desea añadir la tarea compra y verifica el limite 
    private void jLabelCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCompraMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Hacer la compra'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Hacer la compra");

            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_jLabelCompraMouseClicked
    //Pregunta al usuario si desea añadir la tarea Cuidar animales  y verifica el limite 

    private void jLabelCuidarAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuidarAnimalesMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Pasear mascota'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Pasear mascota");

            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_jLabelCuidarAnimalesMouseClicked
    //Pregunta al usuario si desea añadir la tarea cuidar plantas y verifica el limite 

    private void jLabelCuidarPlantasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuidarPlantasMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Regar plantas'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Regar plantas");

            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_jLabelCuidarPlantasMouseClicked
    //Pregunta al usuario si desea añadir la tarea correr y verifica el limite 

    private void jLabelCorrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorrerMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Regar plantas'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Regar plantas");

            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_jLabelCorrerMouseClicked
    //Pregunta al usuario si desea añadir la tarea Ir a peluquería y verifica el limite 

    private void jLabelPeluqueriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPeluqueriaMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Asisitir peluquería'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Asistir peluquería");

            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_jLabelPeluqueriaMouseClicked
    //Pregunta al usuario si desea añadir la tarea leer y verifica el limite 
    private void jLabelLeerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLeerMouseClicked
        int r = JOptionPane.showConfirmDialog(this, "¿Estas seguro de añadir la tarea 'Leer un libro'?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION && this.getContadorT() < 6) {
            paneltarea("Leer un libro");
            JOptionPane.showMessageDialog(this, "Tarea añadida con éxito", "Información", JOptionPane.PLAIN_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Tarea no añadida, recuerda que el limite es 6", "Información", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jLabelLeerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JLabel jLabelCompra;
    private javax.swing.JLabel jLabelCorrer;
    private javax.swing.JLabel jLabelCuidarAnimales;
    private javax.swing.JLabel jLabelCuidarPlantas;
    private javax.swing.JLabel jLabelLeer;
    private javax.swing.JLabel jLabelPeluqueria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEleccion;
    private javax.swing.JPanel jPanelImgs;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelañadirT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTabla;
    private jpanelPersonalizado.JpanelTitulo jpanelTitulo1;
    // End of variables declaration//GEN-END:variables
}
