/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestortareas;

import java.applet.AudioClip;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class Tarea extends javax.swing.JPanel {

    private GestorTareasF gestor; //Almacenamos la referencia al objeto GestorTareas 
//

    /**
     * Creates new form tarea
     */
    public Tarea() {

    }

    public Tarea(GestorTareasF gestor) {
        initComponents();
        this.gestor = gestor;
    }

    public JLabel getjLabelMensaje() {
        return jLabelMensaje;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        setPreferredSize(new java.awt.Dimension(280, 100));
        setLayout(new java.awt.BorderLayout());

        jLabelMensaje.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText("Tarea");
        add(jLabelMensaje, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 1, 0));

        jButtonEliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eliminar.png"))); // NOI18N
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setFocusPainted(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar);

        jButtonConfirmar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonConfirmar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cheque.png"))); // NOI18N
        jButtonConfirmar.setBorderPainted(false);
        jButtonConfirmar.setFocusPainted(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar);

        jButtonEditar.setBackground(new java.awt.Color(51, 51, 255));
        jButtonEditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/editar.png"))); // NOI18N
        jButtonEditar.setPreferredSize(new java.awt.Dimension(50, 10));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    //Se ejecuta cuando le damos clic al botón de eliminar 
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        //Obtenemos el contenedor padre de esta tarea 
        java.awt.Container padre = this.getParent();
        //Actualiza el contador total de paneles, al eliminar 1, entonces restamos 1

        gestor.setContadorT(gestor.getContadorT() - 1);
        //La tarea se elimina del contenedor y actualizamos y volvemos a 
        //pintarla para que se reflejen los cambios. 
        padre.remove(this);
        padre.revalidate();
        padre.repaint();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    //Este metodo se ejecuta cuando se hace clic en el botón editar, permite mdificar 
    //el texto de la tarea. 
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        GestorTareasF p = new GestorTareasF();
        //Instancia "Editar" que permite editar el texto de la tarea
        Editar ed = new Editar(p, jLabelMensaje.getText());
        //Lo hacemos visible para que el usuario pueda modificar el texto de la 
        //tarea 
        ed.setVisible(true);
        //Obtenemos el nuevo texto modificado, si es nulo o vacio no se actualiza 
        String textmod = ed.textomod();
        if (textmod != null && !textmod.trim().isEmpty()) {
            jLabelMensaje.setText(textmod);

            java.awt.Container padre = this.getParent();
            padre.revalidate();
            padre.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Estás intentando introducir una tarea vacía.", "Tarea vacía", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_jButtonEditarActionPerformed
//Este metodo se ejecuta cuando se hace clic en el botón de confirmar
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        AudioClip Sound;
        //reproduce un sonido para confirmar que la tarea fue completada 
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audios/notif.wav"));
        Sound.play();

        //Mover la tarea completada a la tabla jTable 
        //Obtenemos el mensaje de la tarea 
        String tareaTexto = jLabelMensaje.getText();
        //Obtenemos la fecha en la que se completo la tarea 
        String fecha = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm dd-MM-yyyy"));
        java.awt.Container padre = this.getParent();

        //Agregamos la tarea a la tabla y eliminamos la tarea de nuestro panel
        gestor.agregarTareaC(tareaTexto, fecha);
        padre.remove(this);
        padre.revalidate();
        padre.repaint();
        //Modificamos el contador total de paneles 
        gestor.setContadorT(gestor.getContadorT() - 1);
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    //Metodo para que se establezca el asunto de la tarea introducida por el usuario 
    public void nuevoMensaje(String m) {
        jLabelMensaje.setText(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
