/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica8;

import java.util.Arrays;
import java.util.Scanner;
import javafx.scene.control.ButtonBar;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarde
 */
public class Juego extends javax.swing.JDialog {

    /**
     * Creates new form juego
     */
    private String nombre;
    public Juego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        juego();
        

    }

    public Juego(String nombre) {
        this.nombre = nombre;
        
    }

    public String getNombre() {
        return nombre;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        Scanner teclado=new Scanner(System.in);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Juego dialog = new Juego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        


    }

    private void juego() {
        
        this.nombre= JOptionPane.showInputDialog(this, "Introduce tu nombre","Pregunta",JOptionPane.QUESTION_MESSAGE);

        JOptionPane.showMessageDialog(this, "¿Qué personaje quieres ser "+this.getNombre()+" ?","Pregunta",JOptionPane.INFORMATION_MESSAGE);
        JList list=new JList(new String[] {"alfil","caballo","torre"});
        JOptionPane.showMessageDialog(null, list,"Elige un personaje: ",JOptionPane.PLAIN_MESSAGE);
        int resultado=0;
           do{
                resultado= JOptionPane.showConfirmDialog(this, this.getNombre()+" has elegido "+Arrays.toString(list.getSelectedIndices())+", muy buena elección, pero ¿estás completamente seguro de tu elección?","Confirmación",JOptionPane.YES_NO_OPTION);

                    System.out.println(Arrays.toString(list.getSelectedIndices()));
           }while(resultado!=JOptionPane.YES_OPTION);
           
           JOptionPane.showMessageDialog(this, "Bienvenid@ a MathGames","Pregunta",JOptionPane.INFORMATION_MESSAGE);

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
