/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego2d;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author Tarde
 */
public class JuegoPanel extends javax.swing.JPanel implements ActionListener{

    private Timer timer;
    private int x, y, velX, velY;
    /**
     * Creates new form JuegoPanel
     */
    public JuegoPanel() {
        initComponents();
        setBackground(Color.BLACK);
        setFocusable(true);
        addKeyListener(new TAdapter());
        x = 50;
        y = 50;
        velX = 0;
        velY = 0;
        timer = new Timer(10, this);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        dibujar(g);
    }

    
    @Override
    public void actionPerformed(ActionEvent e) {
        mover();
        repaint();
    }

    private void dibujar(Graphics g) {
g.setColor(Color.RED);
        g.fillRect(x, y, 30, 30); // Dibujamos un cuadrado
    }

    private void mover() {
        x +=velX;
        y +=velY;
        
    }

    private class TAdapter extends KeyAdapter {
    @Override
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();

        if (key == KeyEvent.VK_LEFT) {
            velX = -2;
        }

        if (key == KeyEvent.VK_RIGHT) {
            velX = 2;
        }

        if (key == KeyEvent.VK_UP) {
            velY = -2;
        }

        if (key == KeyEvent.VK_DOWN) {
            velY = 2;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        int key = e.getKeyCode();

        if (key == KeyEvent.VK_LEFT || key == KeyEvent.VK_RIGHT) {
            velX = 0;
        }

        if (key == KeyEvent.VK_UP || key == KeyEvent.VK_DOWN) {
            velY = 0;
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


