/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad1_bingo;

import static actividad1_bingo.Actividad1_Bingo.carton;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarde
 */
public class Bingo extends javax.swing.JFrame {

    static int carton[][] = new int[5][5];

    /**
     * Creates new form Bingo
     */
    public Bingo() {
        Actividad1_Bingo a = new Actividad1_Bingo();
        initComponents();
        carton = (int[][]) a.mostrarCarton();
        jTextArea.setText(verCarton());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea = new javax.swing.JTextArea();
        jButtonGenerarNumero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setEnabled(false);
        jPanel1.add(jTextArea);

        jButtonGenerarNumero.setText("Generar número");
        jButtonGenerarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButtonGenerarNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonGenerarNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNumeroActionPerformed
        int n = 0;
        n = (int) (Math.random() * 75) + 1;

        jLabel1.setText(n + "");
        boolean ganar = false;
        if (!ganar) {
            if (buscaNum(n)) {
                //Cambiamos el numero encontrado por un "0"
                cambiarNum(n);
                //Comprobamos si el jugador gano o  no
                //Se gana si se completa una fila entera, una columna o una diagonal
                ganar = comprobarEstado();

                //Ver el carton en su nuevo estado 
                jTextArea.setText(verCarton());
            }
        } else {
            jButtonGenerarNumero.setEnabled(false);
        }


    }//GEN-LAST:event_jButtonGenerarNumeroActionPerformed

    private boolean comprobarEstado() {

        //Comprobar si alguna fila esta completa
        int f = 0;
        boolean ganar = false;
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (carton[fila][col] == 0) {
                    f++;
                }
            }
            if (f == 5) {
                ganar = true;
                JOptionPane.showMessageDialog(this, "Completaste una fila", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);
                return ganar;
            } else {
                f = 0;
            }
        }
        //Comprobar si alguna columna esta completa
        f = 0;
        for (int col = 0; col < 5; col++) {
            for (int fila = 0; fila < 5; fila++) {
                if (carton[fila][col] == 0) {
                    f++;
                }
            }
            if (f == 5) {
                ganar = true;
                JOptionPane.showMessageDialog(this, "Completaste una columna", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

                return ganar;
            } else {
                f = 0;
            }
        }

        //Comprobar la diagonal que empieza en 00 
        f = 0;
        for (int col = 0; col < 5; col++) {
            for (int fila = 0; fila < 5; fila++) {
                if (col == fila) {
                    if (carton[fila][col] == 0) {
                        f++;
                    }
                }
            }
        }
        if (f == 5) {
            ganar = true;
            JOptionPane.showMessageDialog(this, "Completaste una diagonal", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

            return ganar;
        } else {
            f = 0;
        }

        //Comprobar la segunda diagonal
        f = 0;
        ganar = false;
        int col = 4;
        for (int fila = 0; fila < 5; fila++) {

            if (carton[fila][col] == 0) {
                f++;

            }
            col--;
        }
        if (f == 5) {
            ganar = true;
            JOptionPane.showMessageDialog(this, "Completaste una diagonal", "Ganaste!", JOptionPane.INFORMATION_MESSAGE);

            return ganar;
        } else {
            f = 0;
        }

        return ganar;

    }

    private void cambiarNum(int valor) {
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (valor == carton[fila][col]) {
                    carton[fila][col] = 0;
                }
            }
        }
    }

    public static boolean buscaNum(int valor) {
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                if (valor == carton[fila][col]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static String verCarton() {
        String mensaje = "";
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                mensaje = mensaje + carton[fila][col] + "\t";
            }
            mensaje = mensaje + "\n";
        }
        return mensaje;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

}
