/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImagenDemo;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author fatmo
 */
public class ImageDemo extends javax.swing.JPanel {

    /**
     * Creates new form ImageDemo
     */
    private char[][] tablero; //tablero de 3*3
    private boolean turnoX; //Vemos si es el turno de x
    

    public ImageDemo() {
        initComponents();
        tablero = new char[3][3]; //inicializamos el tablero 
        turnoX = true; //Empieza X con color azul

        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int fil = e.getY() / (getHeight() / 3); // sacamos la fila
                int col = e.getX() / (getWidth() / 3); // sacamos la columna

                 // Verifica si la casilla está vacía
                if (tablero[fil][col] == '\u0000') { //'u0000' indica que esta vacia 
                    //si ya toco x entonces tocaria o y viceversa
                    if (turnoX) {
                        // Turno de X: Pinta azul
                        tablero[fil][col] = 'X'; 
                    } else {
                        // Turno de O: Pinta rojo
                        tablero[fil][col] = 'O';
                    }
                    //lo ponemos dfalse, proque empieza x al inicio con true 
                    //a la proxima si esta negado, se cambiaria a true y asi es como 
                    //se alterna
                    turnoX=!turnoX;
                    repaint(); // Redibuja el tablero
                }

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();

        // Dibujar las líneas del tablero
        g.setColor(Color.BLACK);
        g.drawLine(width / 3, 0, width / 3, height);
        g.drawLine(2 * width / 3, 0, 2 * width / 3, height);
        g.drawLine(0, height / 3, width, height / 3);
        g.drawLine(0, 2 * height / 3, width, 2 * height / 3);

         // Dibujar las X y O
         //recorremos el tablero y donde este x u o lo dibujamos 
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                if (tablero[row][col] == 'X') {
                    g.setColor(Color.BLUE); // Azul para X
                    g.setFont(new Font("Arial", Font.BOLD, 40));
                    //dibujamos la x centrada en la celda
                    g.drawString("X", col * (width / 3) + 50, row * (height / 3) + 70);
                } else if (tablero[row][col] == 'O') {
                    g.setColor(Color.RED); // Rojo para O
                    g.setFont(new Font("Arial", Font.BOLD, 40));
                    //dibujamos la o centrada en la celda
                    g.drawString("O", col * (width / 3) + 50, row * (height / 3) + 70);
                }
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
