/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad5;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class Actividad5 extends javax.swing.JFrame {

    /**
     * Creates new form Actividad5
     */
    public Actividad5() {
        
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        setSize(500,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton.setText("Clic aquí");
        jButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonMouseMoved(evt);
            }
        });
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMousePressed(evt);
            }
        });
        getContentPane().add(jButton);

        jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldCaretUpdate(evt);
            }
        });
        jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFocusLost(evt);
            }
        });
        jTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldMouseEntered(evt);
            }
        });
        getContentPane().add(jTextField);

        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 0, 102));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("          Eventos: ");
        getContentPane().add(jLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseMoved
        jLabel.setText("Eventos: el ratón se movio dentro del botón");
    }//GEN-LAST:event_jButtonMouseMoved

    private void jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseEntered
        jLabel.setText("Eventos: el ratón entró dentro del botón");
    }//GEN-LAST:event_jButtonMouseEntered

    private void jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseExited
        jLabel.setText("Eventos: el ratón salió dentro del botón");
    }//GEN-LAST:event_jButtonMouseExited

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        jLabel.setText("Eventos: se clickeo el botón");
    }//GEN-LAST:event_jButtonMouseClicked

    private void jTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldCaretUpdate
                jLabel.setText("Eventos: se produjeron cambios en el campo de texto");

    }//GEN-LAST:event_jTextFieldCaretUpdate

    private void jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFocusGained
                jLabel.setText("Eventos: el campo de texto tiene el enfoque");

    }//GEN-LAST:event_jTextFieldFocusGained

    private void jTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFocusLost
               jLabel.setText("Eventos: el campo de texto perdió el enfoque");

    }//GEN-LAST:event_jTextFieldFocusLost

    private void jButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMousePressed
        //mouseDown es simplemente el nombre utilizado en otros entornos 
        //para describir lo que en java swing es mousePressed
        jLabel.setText("Eventos: se presiono el botón del ratón sobre el botón");

    }//GEN-LAST:event_jButtonMousePressed

    private void jTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMouseEntered
        jLabel.setText("Eventos: el ratón entró dentro del campo de texto");
    }//GEN-LAST:event_jTextFieldMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
