/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatima Mortahil Chachou
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          this.oculto.setVisible(false); //Hace invisible el icono de la contraseña oculta por defecto
        //Establezco el icono de la ventana 
         this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logo.png")).getImage());
         //Hago que la contraseña al inicio este oculta con asteriscos. 
         txt_pass.setEchoChar('*');
         //Le damos un tamaño fijo a la ventana 
         setSize(490,370);
         //Hacemos que el usuario no pueda modificar el tamaño de nuestra ventana 
         setResizable(false);
         //Hacemos que la ventana se abra centrada 
         setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        oculto = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        buttonlLogin = new javax.swing.JButton();
        jpanelImagen1 = new jpanelimagen.JpanelImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/seguridad-del-usuario.png"))); // NOI18N
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 60, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cerrar.png"))); // NOI18N
        jPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, 70));

        txt_user.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_user.setName("utente"); // NOI18N
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, 40));

        txt_pass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_pass.setName("password"); // NOI18N
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jPanel.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 211, 44));

        oculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/oculto.png"))); // NOI18N
        oculto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultoMouseClicked(evt);
            }
        });
        jPanel.add(oculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 50, 50));

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ojo.png"))); // NOI18N
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 40, 40));

        buttonlLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iniciar-sesion.png"))); // NOI18N
        buttonlLogin.setBorder(null);
        buttonlLogin.setBorderPainted(false);
        buttonlLogin.setOpaque(false);
        buttonlLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlLoginActionPerformed(evt);
            }
        });
        jPanel.add(buttonlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, 30));
        jPanel.add(jpanelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 470, 90));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void ocultoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultoMouseClicked
        //Habilita el jlabel "ver" para poder selecionarlo de nuevo si queremos ver la
        //contraseña
        ver.setVisible(true);
        //desabilita el jlabel "oculto"
        oculto.setVisible(false);
        //Hace que el texto dentro del campo se cambie por asteriscos
        txt_pass.setEchoChar('*');
    }//GEN-LAST:event_ocultoMouseClicked

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        //oculta el jlaber "ver" que es un ojo
        ver.setVisible(false);
        //muestra el jlabel "oculto" que es un ojo tachado
        oculto.setVisible(true);
        //Hace visible el texto dentro del campo
        txt_pass.setEchoChar((char) 0);
    }//GEN-LAST:event_verMouseClicked

    private void buttonlLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlLoginActionPerformed
        String usuario, contraseña;
        usuario = txt_user.getText(); //Obtenemos el texto del campo de usuario
        contraseña = String.valueOf(txt_pass.getPassword()); //Obtenemos el texto del campo contraseña
        if (usuario.matches("[A-Za-zÑñ]+") && !usuario.isEmpty() && !contraseña.isEmpty() ) { //verificamos si el usuario  es correcto y si la contraseña esta rellenada. 
            //Mensaje indicando que accedimos sin problemas
            JOptionPane.showMessageDialog(this, "Accediste con exito", "Login correcto", WIDTH);
            //Declramos un objeto para reproducir sonido
            AudioClip Sound;
            //Cargamos el sonido
            Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audios/Login.wav"));
            Sound.play(); //Reproducimos el sonido
            this.dispose(); //Cerramos la ventana de login
            Ventana v2 = new Ventana(this,true); //Crea una instancia de la segunda ventana 
            // Hacemos visible la ventana
            v2.setVisible(true);

        } else { //si el usuario es incorrectos
            //Nos lanza un mensaje de error
            JOptionPane.showMessageDialog(this, "Error.Revisa el usuario no puede contener números, ni los campos deben de estar vacios", "Login incorrecto", JOptionPane.ERROR_MESSAGE);
            txt_user.setText(""); //Limpia el campo de usuario
            txt_pass.setText(""); //Limpia el campo de contraseña

        }
    }//GEN-LAST:event_buttonlLoginActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonlLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private jpanelimagen.JpanelImagen jpanelImagen1;
    private javax.swing.JLabel oculto;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
