/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fatima Mortahil Chachou 
 */
public class Tabla extends javax.swing.JDialog {
private DefaultTableModel modeloTabla;
    /**
     * Creates new form Tabla
     */
    public Tabla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
           setLocationRelativeTo(null); //Para que aparezca en el centro de la pantalla
        initComponents();
        
        setSize(800,300);
        setResizable(false);
        setLocationRelativeTo(null);
        
         modeloTabla = new DefaultTableModel() { //Define el modelo de la tabla 
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //Evita que las celdas de la tabla sean editables. 
            }
        };
          modeloTabla.setColumnIdentifiers(new String[] { "NIT", "Nombre de empresa", "Teléfono", "Ciudad", "Consulta","Email" });
          
           jTable1.setModel(modeloTabla);
         refrescarTabla();
         
    }

    private void refrescarTabla(){
        
        for(Prov p: Lista.getListaProveedores()){ //Para cada proveedor de la lista 
            String[]fila=new String[6]; //Creamos un Array de Strings
            fila[0]=p.getNit();
            fila[1]=p.getNombreEmpresa();
            fila[2]=p.getTelefono();
            fila[3]=p.getCiudad();
            fila[4]=p.getConsulta();
            fila[5]=p.getEmail();
            
            modeloTabla.addRow(fila);
        }
         
    }
    public Tabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }
    
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
